version: '3.8'

services:
  airflow:
    build: .
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: /dags
        target: /opt/airflow/dags
      - type: bind
        source: data
        target: /data
    